### PR TITLE
Check in

### PR DESCRIPTION
**Pull request by pjconnolly12**
Updated the Check In form with the following features:
Validation
Removed Hardcoding
Submission Message
Close Button

Also added a button on the dashboard to open the check-in (this may be changed in the future to a more creative button, ex. a plus sign)

image

image

image

### CODE REVIEW

**Comment by pjconnolly12** [comment]
**UPDATE**
I also added some logic so the users get the correct options on the dashboard. 

If the user has a habit then they will not see the "Create New Habit" button, they will only see the "Check In" button
and vice versa, if they are new and do not have a habit then the new entry form will open (this was already built in) but if the user clicks exit without creating the habit, they will only see the "Create New Habit" button, and not the "Check In" button.

**Review by paulywill — APPROVED** [review]
LGTM!

**Comment by pjconnolly12** [comment]
I'm going to wait to merge, I found an error upon testing, working through it now. if I can't figure out before bed I'll just merge and then resolve the error in a new PR.

**Comment by pjconnolly12** [comment]
**FINAL UPDATE**
Through some testing I realized that when a new user cretaed a new habit the data wasn't pulled through so the dashboard couldn't render. I was able to solve this by passing the data from the habit they create directly to the dashboard.

**Pull request merged**
