### PR TITLE
🔨🐛 - adding 404 page not found component

### PR DESCRIPTION
**Pull request by paulywill**
Ugly but functional 404 page not found #49

image

### CODE REVIEW

**Review by SaraSweetie — CHANGES_REQUESTED** [review]
- Does this page appear with a header? Maybe import the `<Header>` component? If you do that I would suggest to make your `<h1>` into an `<h2>`, for accessibility.

- Also you can delete the `<h2>404 Error</h2> <p>App.js is the defualt page.</p>` Since we have an error page that is no longer needed.

**Comment by paulywill** [comment]
> * Does this page appear with a header? Maybe import the `<Header>` component? If you do that I would suggest to make your `<h1>` into an `<h2>`, for accessibility.
> * Also you can delete the `<h2>404 Error</h2> <p>App.js is the defualt page.</p>` Since we have an error page that is no longer needed.

@SaraSweetie Changed to h2; removed "404 error" from App.js.
Even made edit in alt=, removing the word "image" to resolve console warning.

I suspect some CSS is required for <h2>

image

**Comment by SaraSweetie** [comment]
- @paulywill  If you replace your `<div>` wrapper with `<main>` that will wrap your content in the white background with the blue border. 

- The gecko looks good on the plain background. You could also just write a class on your `<div>` and copy the `<main>` styles except the bg color and border styles.

- for the link you can add the class submit, and that will style it like our form buttons. You may have to adjust the width property since you have more than one word for the button text. `min-width:110px` might fix that

**Comment by paulywill** [comment]
To be honest I sort of like the original error message :/

image

I was trying to be cute with our team's name.... might combine the style of the two

**Comment by paulywill** [comment]
how's this?

image

**Pull request closed without merging**
