### PR TITLE
Newhabit

### PR DESCRIPTION
**Pull request by pjconnolly12**
Here is the newhabit form with form validation and when you submit it creates a new entry on the database.

I used Axios to complete the POST from the front-end

### CODE REVIEW

**Review by paulywill — CHANGES_REQUESTED** [review]
@pjconnolly12 I have not pulled this PR to test yet via `hub pr checkout 42` 
however just reviewing the code here on Github I see you have an old merge conflict message you may have forgotten to remove from App.js (line 30):

```>>>>>>> 36051389cb3ad1d66505481114de9bf79982fa14```

image

**Comment by pjconnolly12** [comment]
Oh man!! When I first went to push this I had a merge conflict that I resolved but I must have missed one somehow. I'm surprised I was able to get it to this point with that conflict. Should I pull this back and fix and then re-submit?

**Comment by paulywill** [comment]
> Oh man!! When I first went to push this I had a merge conflict that I resolved but I must have missed one somehow. I'm surprised I was able to get it to this point with that conflict. Should I pull this back and fix and then re-submit?

Make the change; commit; and then push to your fork
```git push origin newhabit```

Since you are making a PR with your fork it should update here automagically. :unicorn:

You could technically edit the file here on Github as well.

**Comment by pjconnolly12** [comment]
sounds good, I will do that in a bit on my lunch break

**Review by paulywill — APPROVED** [review]

**Comment by paulywill** [comment]
LGTM!

There does appear to some double line action happening under the "New Habit"... but that's minor IMO.

image

**Comment by pjconnolly12** [comment]
yes, that was something I mistakenly added when doing the CSS...but I then thought it looked kind of cool so I left it to see what others thought. very easy to fix if we want to remove it.

**Pull request merged**
