### PR TITLE
Fix/heroku host

### PR DESCRIPTION
**Pull request by paulywill**
This is quite an extensive PR change.

I essentially followed two tutorials (thank you @patricktownley !!!):
- https://daveceddia.com/create-react-app-express-backend/
- https://daveceddia.com/deploy-react-express-app-heroku/

The result after running several tests was the following solved sticking points:

1. File structure change, move the server code into root and rename `Habit-Tracker` to `client`  

2. Added ` "heroku-postbuild": "cd client && npm install && npm run build",` to the package.json for the server. This would build the CRA on the heroku hosting site after `git push heroku master` (which is another remote branch you setup as part of heroku)

3. Added:
 `var path = require('path');` 
`app.use(express.static(path.join(__dirname, 'client/build')));` 
in the index.js (server) this is the first file loaded and indicates to use the CRA code in the client/build directory

4. adding `"proxy": "http://localhost:5000",` in the package.json for the CRA 

Obviously this is based on two tutorials without any further in depth research or understanding... but I think with will load correctly on Heroku and give a nice starting point to build on.

N.B. I setup a pipeline on Heroku for both our `development` and `master` branches:

image

WHICH MEANS.... in theory, after committing this PR to `development` that our app with be available here: https://habit-tracker-gecko-develop.herokuapp.com/

And the same for commiting to `master`: https://habit-tracker-gecko.herokuapp.com/

### CODE REVIEW

**Review by patricktownley — COMMENTED** [review]
So:

A) Awesome - looks like we heroku building the react frontend automatically, and express serving the react frontend from the build folder
B) I can't seem to hit the API on heroku (/api/habits).

I'm gonna check this out and dig in a little further!  Entirely possible I am just doing something wrong on my end.

**Comment by paulywill** [comment]
> So:
> 
> A) Awesome - looks like we heroku building the react frontend automatically, and express serving the react frontend from the build folder
> B) I can't seem to hit the API on heroku (/api/habits).
> 
> I'm gonna check this out and dig in a little further! Entirely possible I am just doing something wrong on my end.

@patricktownley No, you're absolutely right.

I'm seeing the following on heroku:
```2019-03-23T14:59:59.037153+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/api/habits" host=enigmatic-harbor-63388.herokuapp.com request_id=9748ea55-2157-4229-b98d-5d28f0d3a427 fwd="192.0.211.213" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0 protocol=https```

**Comment by patricktownley** [comment]
So it looks like we're running up against an IP whitelisting issue:

It works if I temporarily allow global access:

image

However that's probably not our desired permanent solution.

**Review by patricktownley — APPROVED** [review]
I'm still going to approve this because the code is good to go!  

I'll open a separate issue for the IP whitelisting.

**Pull request merged**
