### PR TITLE
Dotenv configuration for backend

### PR DESCRIPTION
**Pull request by patricktownley**
Added dotenv module to backend and remove keys.js file from the repo.

Express now loads DB key from .env file instead. 

Listed config info in our private docs. 

--------------------

This PR also includes:
Minor touchup to package.json - simply tells it everytime you npm install the main project, also npm install the client.

### CODE REVIEW

**Comment by patricktownley** [comment]
So I meant this to be 2 separate pull requests :/

**Review by paulywill — COMMENTED** [review]
LGTM locally!

**Review by paulywill — APPROVED** [review]
This appears to work locally but confused or not sure why Travis is failing.

**Comment by paulywill** [comment]
Restarted build... I'm think it's failing for reasons outside of our changes and something to do with a node package.

**Pull request merged**
